### ISSUE TITLE
Multi-GPUs usage

### ISSUE THREAD

**Issue by akkasi** [guidance-ai/guidance#525]
Hi,
Could you please let me know how I can use the guidance with multi-gpu settings? I tried **models.transformers(modelname, device-map='auto')**, but checking with nvidia-smi during the inference time, I see that the GPUs are not used.

**Comment by slundberg** [comment]
Hmm. It should just pass those params to the underlying transformers model. I have a single GPU box right now though so it is hard for me to test. If you find more details I can comment though.

**Comment by aadityabhatia** [comment]
`device_map="auto"` works for me. That underscore might be the issue.
